# 시장별 우세 품목 확인 (13_20년도_5대시장_거래량_통합)

### import

In [1]:
import pandas as pd
import numpy as np
import os

import datetime
from datetime import date, timedelta

import warnings
warnings.filterwarnings(action='ignore')

### 도매 가격 종합 데이터셋 input

In [2]:
path = '../data/거래량/원본/'
file_list = os.listdir (path)
file_list_py = [file for file in file_list if '.xlsx' in file]
file_list_py

['2013_5대시장_반입물량_여름포함.xlsx',
 '2014_5대시장_반입물량_여름포함.xlsx',
 '2015_5대시장_반입물량_여름포함.xlsx',
 '2016_5대시장_반입물량_여름포함.xlsx',
 '2017_5대시장_반입물량_여름포함.xlsx',
 '2018_5대시장_반입물량_여름포함.xlsx',
 '2019_5대시장_반입물량_여름포함.xlsx',
 '2020_5대시장_반입물량_여름포함.xlsx',
 '2021_5대시장_반입물량_여름포함.xlsx']

### 데이터셋 concat.

In [3]:
반입물량 = pd.DataFrame()

for files in file_list_py :
    df = pd.read_excel(path + files)
    
    df.drop([0, 1], inplace = True)
    df.drop(df[df['거래년월일'] == '소계'].index, inplace = True)
    
    df.reset_index(drop = True, inplace = True)
    df.rename(columns = {'거래년월일':'날짜'}, inplace = True)
    
    df['날짜'] = pd.to_datetime(df['날짜'])
    df['거래량'] = df['거래량'].str.replace(',', '')
    #df[['시장코드', '출하지코드', '거래량', '품목코드']] = df[['시장코드', '출하지코드', '거래량', '품목코드']].astype(int)
    df.drop(['시장코드', '출하지코드', '품목코드'], axis = 1, inplace = True)    
    
    mapDict = {'봄배추' : '봄',
               '고냉지배추' : '여름', 
               '여름배추' : '여름', 
               '김장(가을)배추' : '가을', 
               '월동배추' : '겨울'}
    df['품목명'] = df['품목명'].apply(lambda x : mapDict[x])
    
    반입물량 = pd.concat([반입물량, df])
    
반입물량

             날짜 품목명       시장명         출하지명    거래량
0    2013-12-31   봄  광주각화도매시장     광주광산구송정동    120
1    2013-12-30   봄  광주각화도매시장     광주광산구송정동    120
2    2013-12-28   봄  광주각화도매시장     광주광산구송정동    180
3    2013-12-28   봄  서울가락도매시장   전라남도진도군진도읍   1500
4    2013-12-27   봄  광주각화도매시장     광주광산구송정동    120
...         ...  ..       ...          ...    ...
5588 2021-06-22  여름  광주각화도매시장  강원도춘천시중앙로3가   9840
5589 2021-06-21  여름  광주각화도매시장  강원도춘천시중앙로3가   9840
5590 2021-06-18  여름  광주각화도매시장  강원도춘천시중앙로3가   9890
5591 2021-06-17  여름  광주각화도매시장  강원도춘천시중앙로3가   9810
5592 2021-06-15  여름  광주각화도매시장  강원도춘천시중앙로3가  10250

[71006 rows x 5 columns]

In [4]:
# ## For Debug.
# ## 일자 연속성 확인
# df = pd.DataFrame(columns = ['날짜'])

# df['날짜'] = 반입물량['날짜'].apply(lambda x : str(x)).sort_values().unique()
# df['날짜'] = df['날짜'].str.split(' ')
# df['날짜'] = df['날짜'].apply(lambda x : str(x[0][:10]))

# prev_date = df['날짜'][0]
# td = timedelta(days = 1)

# for dt in df['날짜'] :
#     if dt != date.isoformat(date.fromisoformat(prev_date) + td) :
#         print(prev_date, dt)
#     prev_date = dt

### 시장별 각 품목별 총 거래량 합산

In [5]:
반입물량['거래량'] = 반입물량['거래량'].apply(lambda x : int(x))
반입물량_시장별 = pd.DataFrame(반입물량.groupby(['날짜', '품목명', '시장명'])['거래량'].sum()).reset_index()
반입물량_시장별

              날짜 품목명       시장명     거래량
0     2013-01-02  가을  광주각화도매시장   19514
1     2013-01-02  가을  대전오정도매시장   20390
2     2013-01-02  겨울  광주각화도매시장   24668
3     2013-01-02  겨울  부산엄궁도매시장    8000
4     2013-01-03  가을  광주각화도매시장   14006
...          ...  ..       ...     ...
14624 2021-12-31  가을  광주각화도매시장   18700
14625 2021-12-31  가을  대전오정도매시장   21690
14626 2021-12-31  가을  부산엄궁도매시장   25000
14627 2021-12-31  가을  서울가락도매시장  263060
14628 2021-12-31  겨울  부산엄궁도매시장  143000

[14629 rows x 4 columns]

In [6]:
반입물량_시장별['시장명'].unique()

array(['광주각화도매시장', '대전오정도매시장', '부산엄궁도매시장', '대구북부도매시장', '서울가락도매시장'],
      dtype=object)

In [7]:
반입물량_시장별['시장명'] = 반입물량_시장별['시장명'].apply(lambda x : x[:2])
반입물량_시장별.columns = ['날짜', '품명', '시장', '거래량']
반입물량_시장별 = 반입물량_시장별[['날짜', '시장', '품명', '거래량']]
반입물량_시장별

              날짜  시장  품명     거래량
0     2013-01-02  광주  가을   19514
1     2013-01-02  대전  가을   20390
2     2013-01-02  광주  겨울   24668
3     2013-01-02  부산  겨울    8000
4     2013-01-03  광주  가을   14006
...          ...  ..  ..     ...
14624 2021-12-31  광주  가을   18700
14625 2021-12-31  대전  가을   21690
14626 2021-12-31  부산  가을   25000
14627 2021-12-31  서울  가을  263060
14628 2021-12-31  부산  겨울  143000

[14629 rows x 4 columns]

### 데이터셋 파일 저장

In [8]:
반입물량_시장별.to_csv('../data/거래량/13_21년도_5대시장_거래량_종합.csv', encoding = 'utf-8-sig')