# [가뭄지수 + 생산량 + 재배면적 + 종합유가 + 도매가] 데이터셋 작성

### import

In [1]:
import os
import numpy as np
import pandas as pd
import statistics
import datetime
from datetime import date, timedelta
from dateutil.relativedelta import relativedelta
import datetime as dt 
import warnings
warnings.filterwarnings(action='ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 500)

### 데이터셋 input

In [2]:
## 예측가격 결정요인
가뭄지수 = pd.read_csv("../data/가뭄/2013_2020_가뭄지수데이터.csv", index_col = 0)
면세유가 = pd.read_csv("../data/유가/13_21_면세유가.csv", index_col = 0)
일반유가 = pd.read_csv("../data/유가/원본/13_21_주유소_지역별_평균판매가격.csv", encoding = "CP949")
면적생산 = pd.read_csv("../data/재배면적_생산량/2013_2020_주요지역_재배면적_생산량.csv", index_col = 0)
수입량 = pd.read_csv("../data/수입량/2013_2021월간배추수입량.csv", encoding = "CP949", names=["연도", "월", "수출(중량)", "수출(금액)", "수입(중량)", "수입(금액)"], thousands = ',')

## 관측지점 관련 데이터
addr = pd.read_excel('../data/지역/한국행정구역분류_2022.7.1.기준_20220630022706.xlsx', sheet_name = 1, header = [2, 2])
addr.drop('Unnamed: 0_level_0', axis = 1, inplace = True)
addr.columns = addr.columns.droplevel(1)
ori_coords = pd.read_excel('../data/지역/행정구역별_위경도_좌표.xlsx', sheet_name = None)
obPoints = pd.read_csv('../data/지역/관측지점_원본_기상청.csv')

### 태백시의 가뭄지수 결측치에 대한 대체값(최인접 지점-봉화군(결측)-울진군) 적용

In [3]:
태백측정일자 = list()
for item in 가뭄지수[가뭄지수['시군명'] == '태백시']['발표일자'].unique() :
    태백측정일자.append(item)

가뭄지수_울진 = 가뭄지수[가뭄지수['시군명'] == '울진군']
가뭄지수_울진_추출 = 가뭄지수_울진[가뭄지수['발표일자'].apply(lambda x : x in 태백측정일자) == False]

## 추출된 울진지점 정보에 태백시 대입
가뭄지수_울진_추출['지점명'] = '태백'
가뭄지수_울진_추출['시군명'] = '태백시'
#가뭄지수_울진_추출['시도명'] = '강원'
가뭄지수_울진_추출

가뭄지수 = pd.concat([가뭄지수, 가뭄지수_울진_추출], ignore_index = True)
가뭄지수

              발표일자  지점명  시군명  SPI1 SPI1_가뭄단계  SPI3 SPI3_가뭄단계   EDI EDI_가뭄단계
0       2013-01-01   속초  고성군  0.47        정상 -0.46        정상 -0.71    약한 가뭄
1       2013-01-01   철원  철원군   NaN       미판단   NaN       미판단   NaN      미판단
2       2013-01-01  대관령  평창군  1.00        습함 -0.73        정상 -1.08    보통 가뭄
3       2013-01-01   춘천  춘천시  1.42        습함  1.46        습함  0.51       정상
4       2013-01-01   강릉  강릉시  0.41        정상 -1.45     약한 가뭄 -0.62       정상
...            ...  ...  ...   ...       ...   ...       ...   ...      ...
184796  2017-12-28   태백  태백시 -0.74        정상 -0.13        정상 -0.75    약한 가뭄
184797  2017-12-29   태백  태백시 -0.63        정상 -0.11        정상 -0.78    약한 가뭄
184798  2017-12-30   태백  태백시 -0.55        정상 -0.07        정상 -0.78    약한 가뭄
184799  2017-12-31   태백  태백시 -0.57        정상 -0.12        정상 -0.81    약한 가뭄
184800  2018-01-01   태백  태백시 -0.66        정상 -0.57        정상 -0.81    약한 가뭄

[184801 rows x 9 columns]

## 1. 가뭄지수 + 종합유가(일반유가 + 면세유가)

In [4]:
# ## For Debug.
# ## 일자 연속성 확인
# df = 가뭄지수.sort_values('발표일자')

# df['발표일자'] = df['발표일자'].apply(lambda x : str(x))
# df['발표일자']

# prev_date = df['발표일자'].unique()[0]
# td = timedelta(days = 1)

# for dt in df['발표일자'].unique():
#     if dt != date.isoformat(date.fromisoformat(prev_date) + td) :
#         print(prev_date, dt)
#     prev_date = dt

In [5]:
## 특이하게 저장된 부분들 편집
가뭄지수.replace('포항시남구',"포항시", inplace=True)
가뭄지수.replace('전주시덕진구',"전주시", inplace=True)
가뭄지수.replace('청주시흥덕구',"청주시", inplace=True)
가뭄지수.replace('\xa0서울특별시', '서울특별시', inplace = True)
가뭄지수.replace('\xa0인천광역시', '인천광역시', inplace = True)
가뭄지수.replace('\xa0대전광역시', '대전광역시', inplace = True)
가뭄지수.replace('\xa0대구광역시', '대구광역시', inplace = True)
가뭄지수.replace('\xa0울산광역시', '울산광역시', inplace = True)
가뭄지수.replace('\xa0광주광역시', '광주광역시', inplace = True)
가뭄지수.replace('\xa0부산광역시', '부산광역시', inplace = True)

### 1-1. 가뭄지수 관측지점의 시도명 추출

In [6]:
## 시도명 컬럼 추가
## (time...)
가뭄지수['시도명'] = ''

## 시도명 탐색 후 대입
def helper(target) :
    try :
        ans = addr[addr['시군구'] == target].iloc[0]['시도']
    except :
        ans = addr[addr['시도'] == target].iloc[0]['시도']
        
    if ans[:2] in 면세유가.columns :
        return ans[:2]
    else :
        return (ans[0] + ans[2])

가뭄지수['시도명'] = 가뭄지수['시군명'].apply(lambda x : helper(x))
가뭄지수

,발표일자,지점명,시군명,SPI1,SPI1_가뭄단계,SPI3,SPI3_가뭄단계,EDI,EDI_가뭄단계,시도명
0,2013-01-01,속초,고성군,0.47,정상,-0.46,정상,-0.71,약한 가뭄,강원
1,2013-01-01,철원,철원군,NaN,미판단,NaN,미판단,NaN,미판단,강원
2,2013-01-01,대관령,평창군,1.00,습함,-0.73,정상,-1.08,보통 가뭄,강원
3,2013-01-01,춘천,춘천시,1.42,습함,1.46,습함,0.51,정상,강원
4,2013-01-01,강릉,강릉시,0.41,정상,-1.45,약한 가뭄,-0.62,정상,강원
...,...,...,...,...,...,...,...,...,...,...
184796,2017-12-28,태백,태백시,-0.74,정상,-0.13,정상,-0.75,약한 가뭄,강원
184797,2017-12-29,태백,태백시,-0.63,정상,-0.11,정상,-0.78,약한 가뭄,강원
184798,2017-12-30,태백,태백시,-0.55,정상,-0.07,정상,-0.78,약한 가뭄,강원
184799,2017-12-31,태백,태백시,-0.57,정상,-0.12,정상,-0.81,약한 가뭄,강원
184800,2018-01-01,태백,태백시,-0.66,정상,-0.57,정상,-0.81,약한 가뭄,강원

### 1-2. 일반유가 merge

In [7]:
## 일반유가 Merge
## (time...)

일반유가['구분'] = 일반유가['구분'].str.replace('년', '-')
일반유가['구분'] = 일반유가['구분'].str.replace('월', '-')
일반유가['구분'] = 일반유가['구분'].str.replace('일', '')
일반유가

## 컬럼으로 나누어진 지명을 로우로 변환
일반유가_월별정리 = pd.DataFrame()
for idx in 일반유가.index :
    for col in 일반유가.columns[1:] :
        temp = {'날짜' : 일반유가['구분'][idx], '지역' : col, '일반유가' : 일반유가[col][idx]}
        일반유가_월별정리 = pd.concat([일반유가_월별정리, pd.DataFrame([temp])])

## 가뭄지수-일반유가 Merge
가뭄지수_일반 = pd.merge(가뭄지수, 일반유가_월별정리, left_on = ['발표일자', '시도명'], right_on = ['날짜', '지역'], how = 'left')
가뭄지수_일반

,발표일자,지점명,시군명,SPI1,SPI1_가뭄단계,SPI3,SPI3_가뭄단계,EDI,EDI_가뭄단계,시도명,날짜,지역,일반유가
0,2013-01-01,속초,고성군,0.47,정상,-0.46,정상,-0.71,약한 가뭄,강원,2013-01-01,강원,1762.79
1,2013-01-01,철원,철원군,NaN,미판단,NaN,미판단,NaN,미판단,강원,2013-01-01,강원,1762.79
2,2013-01-01,대관령,평창군,1.00,습함,-0.73,정상,-1.08,보통 가뭄,강원,2013-01-01,강원,1762.79
3,2013-01-01,춘천,춘천시,1.42,습함,1.46,습함,0.51,정상,강원,2013-01-01,강원,1762.79
4,2013-01-01,강릉,강릉시,0.41,정상,-1.45,약한 가뭄,-0.62,정상,강원,2013-01-01,강원,1762.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...
184796,2017-12-28,태백,태백시,-0.74,정상,-0.13,정상,-0.75,약한 가뭄,강원,2017-12-28,강원,1339.69
184797,2017-12-29,태백,태백시,-0.63,정상,-0.11,정상,-0.78,약한 가뭄,강원,2017-12-29,강원,1340.21
184798,2017-12-30,태백,태백시,-0.55,정상,-0.07,정상,-0.78,약한 가뭄,강원,2017-12-30,강원,1340.70
184799,2017-12-31,태백,태백시,-0.57,정상,-0.12,정상,-0.81,약한 가뭄,강원,2017-12-31,강원,1340.84
184800,2018-01-01,태백,태백시,-0.66,정상,-0.57,정상,-0.81,약한 가뭄,강원,2018-01-01,강원,1341.54

### 1-3. 면세유가 merge

In [8]:
## 면세유가 Merge
## (time...)

## 컬럼으로 나누어진 지명을 로우로 변환
면세유가_월별정리 = pd.DataFrame()
for idx in 면세유가.index :
    for col in 면세유가.columns[1:] :
        temp = {'날짜' : 면세유가['날짜'][idx], 
                '지역' : col, 
                '면세유가' : 면세유가[col][idx]}
        면세유가_월별정리 = pd.concat([면세유가_월별정리, pd.DataFrame([temp])])
면세유가_월별정리

## 가뭄지수-면세유가 Merge
가뭄지수_종합유가 = pd.merge(가뭄지수_일반, 면세유가_월별정리, left_on = ['날짜', '지역'], right_on = ['날짜', '지역'], how = 'left')
가뭄지수_종합유가

,발표일자,지점명,시군명,SPI1,SPI1_가뭄단계,SPI3,SPI3_가뭄단계,EDI,EDI_가뭄단계,시도명,날짜,지역,일반유가,면세유가
0,2013-01-01,속초,고성군,0.47,정상,-0.46,정상,-0.71,약한 가뭄,강원,2013-01-01,강원,1762.79,1157.305617
1,2013-01-01,철원,철원군,NaN,미판단,NaN,미판단,NaN,미판단,강원,2013-01-01,강원,1762.79,1157.305617
2,2013-01-01,대관령,평창군,1.00,습함,-0.73,정상,-1.08,보통 가뭄,강원,2013-01-01,강원,1762.79,1157.305617
3,2013-01-01,춘천,춘천시,1.42,습함,1.46,습함,0.51,정상,강원,2013-01-01,강원,1762.79,1157.305617
4,2013-01-01,강릉,강릉시,0.41,정상,-1.45,약한 가뭄,-0.62,정상,강원,2013-01-01,강원,1762.79,1157.305617
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184796,2017-12-28,태백,태백시,-0.74,정상,-0.13,정상,-0.75,약한 가뭄,강원,2017-12-28,강원,1339.69,751.140000
184797,2017-12-29,태백,태백시,-0.63,정상,-0.11,정상,-0.78,약한 가뭄,강원,2017-12-29,강원,1340.21,752.160000
184798,2017-12-30,태백,태백시,-0.55,정상,-0.07,정상,-0.78,약한 가뭄,강원,2017-12-30,강원,1340.70,751.600000
184799,2017-12-31,태백,태백시,-0.57,정상,-0.12,정상,-0.81,약한 가뭄,강원,2017-12-31,강원,1340.84,751.140000
184800,2018-01-01,태백,태백시,-0.66,정상,-0.57,정상,-0.81,약한 가뭄,강원,2018-01-01,강원,1341.54,752.020000

## 2. (가뭄지수+종합유가) + 면적생산

In [9]:
## 연도 컬럼 추가
가뭄지수_종합유가['연도'] = ''
가뭄지수_종합유가['연도'] = 가뭄지수_종합유가['발표일자'].apply(lambda x : x[:4])
가뭄지수_종합유가

,발표일자,지점명,시군명,SPI1,SPI1_가뭄단계,SPI3,SPI3_가뭄단계,EDI,EDI_가뭄단계,시도명,날짜,지역,일반유가,면세유가,연도
0,2013-01-01,속초,고성군,0.47,정상,-0.46,정상,-0.71,약한 가뭄,강원,2013-01-01,강원,1762.79,1157.305617,2013
1,2013-01-01,철원,철원군,NaN,미판단,NaN,미판단,NaN,미판단,강원,2013-01-01,강원,1762.79,1157.305617,2013
2,2013-01-01,대관령,평창군,1.00,습함,-0.73,정상,-1.08,보통 가뭄,강원,2013-01-01,강원,1762.79,1157.305617,2013
3,2013-01-01,춘천,춘천시,1.42,습함,1.46,습함,0.51,정상,강원,2013-01-01,강원,1762.79,1157.305617,2013
4,2013-01-01,강릉,강릉시,0.41,정상,-1.45,약한 가뭄,-0.62,정상,강원,2013-01-01,강원,1762.79,1157.305617,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184796,2017-12-28,태백,태백시,-0.74,정상,-0.13,정상,-0.75,약한 가뭄,강원,2017-12-28,강원,1339.69,751.140000,2017
184797,2017-12-29,태백,태백시,-0.63,정상,-0.11,정상,-0.78,약한 가뭄,강원,2017-12-29,강원,1340.21,752.160000,2017
184798,2017-12-30,태백,태백시,-0.55,정상,-0.07,정상,-0.78,약한 가뭄,강원,2017-12-30,강원,1340.70,751.600000,2017
184799,2017-12-31,태백,태백시,-0.57,정상,-0.12,정상,-0.81,약한 가뭄,강원,2017-12-31,강원,1340.84,751.140000,2017
184800,2018-01-01,태백,태백시,-0.66,정상,-0.57,정상,-0.81,약한 가뭄,강원,2018-01-01,강원,1341.54,752.020000,2018

### 2-1. 각 배추 품종별 최대면적 row 추출

In [10]:
# 계절별 구분 필요
최대값 = pd.DataFrame()
for season in 면적생산['품명'].unique() :
    temp = pd.DataFrame(면적생산[면적생산['품명'] == season].groupby(['연도', '품명'])['면적'].max()).reset_index()
    최대값 = pd.concat([최대값, temp] , ignore_index = True)
최대값

      연도  품명    면적
0   2013   봄   120
1   2014   봄    90
2   2015   봄    60
3   2016   봄   160
4   2017   봄   280
5   2018   봄   175
6   2019   봄   318
7   2020   봄   363
8   2013  겨울  2842
9   2014  겨울  2718
10  2015  겨울  2918
11  2016  겨울  2529
12  2017  겨울  2306
13  2018  겨울  3661
14  2019  겨울  2640
15  2020  겨울  2400
16  2013  가을  1547
17  2014  가을  1648
18  2015  가을  1791
19  2016  가을  1851
20  2017  가을  1892
21  2018  가을  1993
22  2019  가을  1941
23  2020  가을  2488
24  2013  여름  1060
25  2014  여름  1542
26  2015  여름  1360
27  2016  여름  1372
28  2017  여름  1580
29  2018  여름  1260
30  2019  여름  1618
31  2020  여름  1407

### 2-2. 최대면적 해당 지역 및 생산량 탐색

In [11]:
면적생산_최대면적 = pd.DataFrame()
for idx in 최대값.index :
    
    merged = 면적생산[(면적생산['연도'] == 최대값['연도'][idx]) & 
                   (면적생산['품명'] == 최대값['품명'][idx]) &
                   (면적생산['면적'] == 최대값['면적'][idx])]
    
    면적생산_최대면적 = pd.concat([면적생산_최대면적, merged] , ignore_index = True)
면적생산_최대면적['지역'] = 면적생산_최대면적['지역'].replace('예산시', '예산군')

### 2-3. 관측지점 대체 지역 리스트 작성

In [12]:
## 최대면적 해당 지역과 관측지점 불일치로 인한 대체 지역 리스트
noItemLi = list()
for item in 면적생산_최대면적['지역'].unique()  :
    if not item in 가뭄지수_종합유가['시군명'].unique() :
        noItemLi.append(item)

## 관측지점 불일치 지점 목록 DF화
noItemDF = pd.DataFrame(noItemLi, columns = ['시군구'])

## 개정 지명 예외처리
noItemDF.replace('마산시', '창원시', inplace = True)
noItemDF.replace('진해시', '창원시', inplace = True)
noItemDF.replace('예산시', '예산군', inplace = True)
noItemDF.replace('세종특별시', '세종특별자치시', inplace = True)

noItemDF

   시군구
0  예산군
1  정선군

### 2-4. 관측지점 대체를 위한 지점별 좌표 정보 탐색

In [13]:
pd.concat(ori_coords, ignore_index = True)

          시도  시군구 읍면동/구 읍/면/리/동    리         위도          경도
0      서울특별시  NaN   NaN     NaN  NaN  37.566610  126.978388
1      서울특별시  강동구   NaN     NaN  NaN  37.530126  127.123771
2      서울특별시  강동구   천호동     NaN  NaN  37.545016  127.136807
3      서울특별시  강동구   성내동     NaN  NaN  37.530442  127.122425
4      서울특별시  강동구   암사동     NaN  NaN  37.551508  127.132663
...      ...  ...   ...     ...  ...        ...         ...
21811  인천광역시   중구   율목동     NaN  NaN  37.469337  126.635757
21812  인천광역시   중구   도원동     NaN  NaN  37.468094  126.637901
21813  인천광역시   중구   신흥동     NaN  NaN  37.467596  126.634139
21814  인천광역시   중구   신포동     NaN  NaN  37.470363  126.625071
21815  인천광역시   중구   연안동     NaN  NaN  37.453233  126.604535

[21816 rows x 7 columns]

In [14]:
## 행정구역별 좌표 자료
ori_coords = pd.concat(ori_coords, ignore_index = True)

## 개정지명 예외처리
# ori_coords.replace('예산군', '예산시', inplace = True)
# ori_coords.replace('양양군', '양양시', inplace = True)

## 시군구 단위 추출
coords = ori_coords

dropidx = coords[coords['읍면동/구'].isna() == False].index
coords.drop(dropidx, inplace = True)
coords.drop(['읍면동/구', '읍/면/리/동', '리'], axis = 1, inplace = True)
coords.reset_index(drop = True, inplace =True)

#coords.to_csv("./data/지역/전국행정구역좌표정리.csv", encoding = 'utf-8-sig')

coords['시군구'].fillna(coords['시도'], inplace = True)
coords['시군구'].str.strip()

coords

          시도      시군구         위도          경도
0      서울특별시    서울특별시  37.566610  126.978388
1      서울특별시      강동구  37.530126  127.123771
2      서울특별시      송파구  37.514564  127.105919
3      서울특별시      강남구  37.517305  127.047502
4      서울특별시      서초구  37.483569  127.032598
5      서울특별시      관악구  37.478155  126.951485
6      서울특별시      동작구  37.512450  126.939500
7      서울특별시     영등포구  37.526436  126.896004
8      서울특별시      금천구  37.456864  126.895511
9      서울특별시      구로구  37.495472  126.887536
10     서울특별시      강서구  37.550937  126.849642
11     서울특별시      양천구  37.517016  126.866642
12     서울특별시      마포구  37.566325  126.901491
13     서울특별시     서대문구  37.579225  126.936800
14     서울특별시      은평구  37.602784  126.929164
15     서울특별시      노원구  37.654358  127.056473
16     서울특별시      도봉구  37.668768  127.047163
17     서울특별시      강북구  37.639782  127.025614
18     서울특별시      성북구  37.589400  127.016749
19     서울특별시      중랑구  37.606324  127.092584
20     서울특별시     동대문구  37.574524  127.039650
21     서울특별시      광진구  37.538617  127.082375
22     서울특별시      성동구  37.563456  127.036821
23     서울특별시      용산구  37.532527  126.990490
24     서울특별시       중구  37.563843  126.997602
25     서울특별시      종로구  37.573521  126.978835
26       강원도      강원도  37.860367  128.311526
27       강원도      양양군  38.075493  128.619145
28       강원도      고성군  38.380615  128.467862
29       강원도      인제군  38.069732  128.170352
30       강원도      양구군  38.109992  127.990000
31       강원도      화천군  38.106181  127.708216
32       강원도      철원군  38.146861  127.313472
33       강원도      정선군  37.380609  128.660871
34       강원도      평창군  37.370770  128.390193
35       강원도      영월군  37.183774  128.461850
36       강원도      횡성군  37.491803  127.985022
37       강원도      홍천군  37.697207  127.888518
38       강원도      삼척시  37.449935  129.165148
39       강원도      속초시  38.207169  128.591840
40       강원도      태백시  37.164132  128.985735
41       강원도      동해시  37.524758  129.114262
42       강원도      강릉시  37.752175  128.875836
43       강원도      원주시  37.342318  127.919969
44       강원도      춘천시  37.881374  127.730003
45       경기도      경기도  37.436318  127.550802
46       경기도      양평군  37.491791  127.487597
47       경기도      가평군  37.831508  127.509541
48       경기도      연천군  38.096738  127.074755
49       경기도      여주시        NaN         NaN
50       경기도      포천시  37.894867  127.200240
51       경기도      양주시  37.785329  127.045847
52       경기도      광주시  37.429431  127.255048
53       경기도      화성시  37.199565  126.831405
54       경기도      김포시  37.615350  126.715544
55       경기도      안성시  37.008055  127.279773
56       경기도      이천시  37.272342  127.435034
57       경기도      파주시  37.760186  126.779883
58       경기도      용인시  37.241252  127.177492
59       경기도      하남시  37.539301  127.214874
60       경기도      의왕시  37.344887  126.968279
61       경기도      군포시  37.361523  126.935338
62       경기도      시흥시  37.380177  126.802934
63       경기도      오산시  37.149887  127.077462
64       경기도     남양주시  37.635985  127.216467
65       경기도      구리시  37.594266  127.129632
66       경기도      과천시  37.429201  126.987675
67       경기도      고양시  37.658398  126.831983
68       경기도      안산시  37.321912  126.830818
69       경기도     동두천시  37.903662  127.060671
70       경기도      평택시  36.992354  127.112695
71       경기도      광명시  37.478618  126.864650
72       경기도      부천시  37.503592  126.766000
73       경기도      안양시  37.394290  126.956753
74       경기도     의정부시  37.738083  127.033753
75       경기도      성남시  37.420027  127.126777
76       경기도      수원시  37.263476  127.028646
77      경상남도     경상남도  35.441421  128.241745
78      경상남도      합천군  35.566660  128.165799
79      경상남도      거창군  35.686698  127.909538
80      경상남도      함양군  35.520536  127.725245
81      경상남도      산청군  35.415557  127.873458
82      경상남도      하동군  35.067333  127.751275
83      경상남도      남해군  34.837707  127.892475
84      경상남도      고성군  34.973098  128.322264
85      경상남도      창녕군  35.544611  128.492346
86      경상남도      함안군  35.272315  128.406595
87      경상남도      의령군  35.322224  128.261676
88      경상남도      양산시  35.335049  129.037339
89      경상남도      거제시  34.880457  128.621170
90      경상남도      밀양시  35.503856  128.746712
91      경상남도      김해시  35.228574  128.889322
92      경상남도      사천시  35.003477  128.063865
93      경상남도      통영시  34.854390  128.433112
94      경상남도      진주시  35.180325  128.107646
95      경상남도      창원시  35.227877  128.681875
96      경상북도     경상북도  36.630840  128.962578
97      경상북도      울릉군  37.484455  130.905697
98      경상북도      울진군  36.993087  129.400394
99      경상북도      봉화군  36.893114  128.732503
100     경상북도      예천군  36.646884  128.437355
101     경상북도      칠곡군  35.995575  128.401679
102     경상북도      성주군  35.919175  128.282959
103     경상북도      고령군  35.725968  128.262688
104     경상북도      청도군  35.647399  128.733988
105     경상북도      영덕군  36.415034  129.365267
106     경상북도      영양군  36.666717  129.112384
107     경상북도      청송군  36.436279  129.057126
108     경상북도      의성군  36.352716  128.697171
109     경상북도      군위군  36.242945  128.572657
110     경상북도      경산시  35.825090  128.741201
111     경상북도      문경시  36.586522  128.186787
112     경상북도      상주시  36.411002  128.159229
113     경상북도      영천시  35.973260  128.938613
114     경상북도      영주시  36.805667  128.624063
115     경상북도      구미시  36.119599  128.344300
116     경상북도      안동시  36.568425  128.729537
117     경상북도      김천시  36.139771  128.113615
118     경상북도      경주시  35.856242  129.224784
119     경상북도      포항시  36.019033  129.343390
120    광주광역시    광주광역시  35.160032  126.851338
121    광주광역시      광산구  35.139508  126.793683
122    광주광역시       북구  35.174060  126.911963
123    광주광역시       남구  35.133004  126.902402
124    광주광역시       서구  35.151969  126.890272
125    광주광역시       동구  35.146082  126.923286
126    대구광역시    대구광역시  35.871390  128.601763
127    대구광역시      달성군  35.774600  128.431445
128    대구광역시      달서구  35.829867  128.532737
129    대구광역시      수성구  35.858165  128.630625
130    대구광역시       북구  35.885684  128.582947
131    대구광역시       남구  35.846000  128.597486
132    대구광역시       서구  35.871757  128.559175
133    대구광역시       동구  35.886664  128.635609
134    대구광역시       중구  35.869340  128.606200
135    대전광역시    대전광역시  36.350440  127.384951
136    대전광역시      대덕구  36.346735  127.415502
137    대전광역시      유성구  36.362322  127.356268
138    대전광역시       서구  36.355504  127.383844
139    대전광역시       중구  36.325659  127.421546
140    대전광역시       동구  36.312169  127.454884
141    부산광역시    부산광역시  35.179816  129.075022
142    부산광역시      기장군  35.244498  129.222312
143    부산광역시      사상구  35.152624  128.991250
144    부산광역시      수영구  35.145694  129.113186
145    부산광역시      연제구  35.176242  129.079764
146    부산광역시      강서구  35.212218  128.980450
147    부산광역시      금정구  35.243068  129.092100
148    부산광역시      사하구  35.104585  128.974817
149    부산광역시     해운대구  35.163177  129.163634
150    부산광역시       북구  35.197185  128.990438
151    부산광역시       남구  35.136577  129.084163
152    부산광역시      동래구  35.196438  129.093857
153    부산광역시     부산진구  35.162913  129.053157
154    부산광역시      영도구  35.091199  129.067875
155    부산광역시       동구  35.129275  129.045325
156    부산광역시       서구  35.097932  129.024413
157    부산광역시       중구  35.106214  129.032352
158  세종특별자치시  세종특별자치시  36.480351  127.289433
159  세종특별자치시      어진동  36.501231  127.263996
160  세종특별자치시      다정동  36.494607  127.245153
161  세종특별자치시      나성동  36.486328  127.264133
162  세종특별자치시      가람동  36.470355  127.246218
163  세종특별자치시      반곡동  36.491997  127.311484
164  세종특별자치시      대평동  36.471141  127.279515
165  세종특별자치시      보람동  36.478916  127.290643
166  세종특별자치시      소담동  36.483956  127.300415
167  세종특별자치시      고운동  36.519747  127.236668
168  세종특별자치시      종촌동  36.504530  127.246912
169  세종특별자치시      아름동  36.512220  127.246900
170  세종특별자치시      도담동  36.515446  127.261734
171  세종특별자치시      새롬동  36.484856  127.251805
172  세종특별자치시      한솔동  36.479087  127.254686
173  세종특별자치시      소정면  36.722325  127.158256
174  세종특별자치시      전동면  36.662731  127.233690
175  세종특별자치시      전의면  36.681444  127.195956
176  세종특별자치시      연서면  36.592587  127.271622
177  세종특별자치시      장군면  36.496697  127.205633
178  세종특별자치시      금남면  36.463826  127.280350
179  세종특별자치시      부강면  36.529726  127.370920
180  세종특별자치시      연동면  36.555165  127.327405
181  세종특별자치시      연기면  36.541874  127.273774
182  세종특별자치시     조치원읍  36.604566  127.298428
183    울산광역시    울산광역시  35.539477  129.311299
184    울산광역시      울주군  35.522089  129.242230
185    울산광역시       북구  35.582709  129.361313
186    울산광역시       동구  35.504844  129.416632
187    울산광역시       남구  35.543798  129.330109
188    울산광역시       중구  35.569450  129.332700
189     전라남도     전라남도  34.900727  126.957167
190     전라남도      신안군  34.833626  126.351124
191     전라남도      진도군  34.486818  126.263475
192     전라남도      완도군  34.311039  126.754852
193     전라남도      장성군  35.301943  126.784814
194     전라남도      영광군  35.277213  126.512014
195     전라남도      함평군  35.065929  126.516582
196     전라남도      무안군  34.990489  126.481712
197     전라남도      영암군  34.800164  126.696796
198     전라남도      해남군  34.573558  126.599225
199     전라남도      강진군  34.642090  126.767200
200     전라남도      장흥군  34.681622  126.907051
201     전라남도      화순군  35.064524  126.986477
202     전라남도      보성군  34.771458  127.080088
203     전라남도      고흥군  34.604705  127.275507
204     전라남도      구례군  35.202510  127.462937
205     전라남도      곡성군  35.282017  127.291978
206     전라남도      담양군  35.321175  126.988175
207     전라남도      광양시  34.940658  127.695899
208     전라남도      나주시  35.015814  126.710814
209     전라남도      순천시  34.950698  127.487243
210     전라남도      여수시  34.760425  127.662313
211     전라남도      목포시  34.811875  126.392337
212     전라북도     전라북도  35.691015  127.236829
213     전라북도      부안군  35.731755  126.733199
214     전라북도      고창군  35.435836  126.701973
215     전라북도      순창군  35.374476  127.137489
216     전라북도      임실군  35.617829  127.289077
217     전라북도      장수군  35.647366  127.521521
218     전라북도      무주군  36.006810  127.660818
219     전라북도      진안군  35.791762  127.424875
220     전라북도      완주군  35.904708  127.162019
221     전라북도      김제시  35.803592  126.880837
222     전라북도      남원시  35.416432  127.390438
223     전라북도      정읍시  35.569867  126.856038
224     전라북도      익산시  35.948295  126.957786
225     전라북도      군산시  35.967626  126.736875
226     전라북도      전주시  35.824171  127.148050
227  제주특별자치도  제주특별자치도  33.427337  126.575834
228  제주특별자치도     서귀포시  33.253925  126.559787
229  제주특별자치도      제주시  33.499568  126.531138
230     충청남도     충청남도  36.617338  126.845397
231     충청남도      태안군  36.745610  126.297913
232     충청남도      예산군  36.680900  126.844738
233     충청남도      홍성군  36.601324  126.660775
234     충청남도      청양군  36.459151  126.802238
235     충청남도      서천군  36.080286  126.691742
236     충청남도      부여군  36.275658  126.909775
237     충청남도      금산군  36.108857  127.488213
238     충청남도      당진시  36.889974  126.645900
239     충청남도      계룡시  36.274554  127.248633
240     충청남도      논산시  36.187240  127.098623
241     충청남도      서산시  36.784922  126.450277
242     충청남도      아산시  36.790013  127.002474
243     충청남도      보령시  36.333452  126.612803
244     충청남도      공주시  36.446556  127.119040
245     충청남도      천안시  36.815147  127.113892
246     충청북도     충청북도  36.785372  127.655140
247     충청북도      단양군  36.984539  128.365589
248     충청북도      음성군  36.940282  127.690487
249     충청북도      괴산군  36.815381  127.786704
250     충청북도      진천군  36.855420  127.435602
251     충청북도      증평군  36.785345  127.581507
252     충청북도      영동군  36.175047  127.783423
253     충청북도      옥천군  36.306437  127.571419
254     충청북도      보은군  36.489455  127.729485
255     충청북도      제천시  37.132646  128.191037
256     충청북도      충주시  36.991105  127.926012
257     충청북도      청주시  36.642499  127.488975
258    인천광역시    인천광역시  37.455942  126.705151
259    인천광역시      옹진군  37.446607  126.636760
260    인천광역시      강화군  37.746498  126.488052
261    인천광역시       서구  37.545449  126.675994
262    인천광역시      계양구  37.537415  126.737776
263    인천광역시      부평구  37.507056  126.721838
264    인천광역시      남동구  37.447342  126.731488
265    인천광역시      연수구  37.410168  126.678280
266    인천광역시     미추홀구  37.463523  126.650584
267    인천광역시       동구  37.473885  126.643213
268    인천광역시       중구  37.473781  126.621588

### 2-5. 관측지점 불일치 지점의 좌표 정보 mapping

In [15]:
noItemCoordsDF = pd.merge(noItemDF, coords, on = '시군구', how = 'left').drop('시도', axis = 1)
noItemCoordsDF['대체지점명'] = ''
noItemCoordsDF

   시군구         위도          경도 대체지점명
0  예산군  36.680900  126.844738
1  정선군  37.380609  128.660871

### 2-6. 기상청 관측지점 좌표 정보 탐색

In [16]:
## 기상청 관측지점 정보
obPoints.dropna(inplace = True)
obPoints.drop(columns = ['종료시각', '시작시각', '노장 해발고도(m)','기압계', '기온계', '풍속계', '강우계'], inplace = True)
obPoints.columns = ['지점코드', '지점명', '주소', '위도', '경도']
obPoints.reset_index(drop = True)

obPoints.주소 = obPoints.주소.str.split(" ")
region = []
for item in obPoints["주소"]:
    first = item[0]
    second = item[1]
    
    if "시" in second:
        region.append(second)
    elif "군" in second:
        region.append(second)
    elif "시" in first:
        region.append(first)
        
obPoints["주소"] = region

## 원본 데이터 내 이상 데이터 편집
obPoints.replace('포항시남구',"포항시", inplace=True)
obPoints.replace('전주시덕진구',"전주시", inplace=True)
obPoints.replace('청주시흥덕구',"청주시", inplace=True)
obPoints.replace('\xa0서울특별시', '서울특별시', inplace = True)
obPoints.replace('\xa0인천광역시', '인천광역시', inplace = True)
obPoints.replace('\xa0대전광역시', '대전광역시', inplace = True)
obPoints.replace('\xa0대구광역시', '대구광역시', inplace = True)
obPoints.replace('\xa0울산광역시', '울산광역시', inplace = True)
obPoints.replace('\xa0광주광역시', '광주광역시', inplace = True)
obPoints.replace('\xa0부산광역시', '부산광역시', inplace = True)

## 전체 기상청 관측지점 중 가뭄지수 관측 지점에 해당하는 68개 지점 추출
def helper(x) :
    if x in list(가뭄지수['시군명'].unique()) :
        return x
    else :
        np.nan

obPoints['주소'] = obPoints['주소'].apply(lambda x : helper(x))
obPoints.dropna(inplace = True)
obPoints.reset_index(drop = True, inplace = True)

obPoints

    지점코드   지점명     주소         위도          경도
0     90    속초    고성군   38.25085   128.56473
1     95    철원    철원군   38.14787    127.3042
2    100   대관령    평창군   37.67713   128.71834
3    101    춘천    춘천시   37.90262    127.7357
4    104   북강릉    강릉시   37.80456   128.85535
5    105    강릉    강릉시   37.75147   128.89099
6    108    서울  서울특별시   37.57142    126.9658
7    112    인천  인천광역시   37.47772    126.6249
8    114    원주    원주시   37.33749   127.94659
9    119    수원    수원시   37.25746     126.983
10   127    충주    충주시   36.97045    127.9525
11   129    서산    서산시   36.77658    126.4939
12   130    울진    울진군   36.99176   129.41278
13   131    청주    청주시   36.63924   127.44066
14   133    대전  대전광역시   36.37198   127.37211
15   135   추풍령    영동군   36.22025   127.99458
16   136    안동    안동시   36.57293   128.70734
17   138    포항    포항시   36.03201   129.38002
18   140    군산    군산시    36.0053   126.76135
19   143    대구  대구광역시   35.87797   128.65295
20   146    전주    전주시   35.84092   127.11718
21   152    울산  울산광역시   35.58237   129.33469
22   155    창원    창원시   35.17019   128.57281
23   156    광주  광주광역시   35.17294   126.89156
24   159    부산  부산광역시   35.10468   129.03203
25   162    통영    통영시   34.84541   128.43561
26   165    목포    목포시   34.81732   126.38151
27   168    여수    여수시   34.73929   127.74063
28   170    완도    완도군    34.3959   126.70182
29   184    제주    제주시   33.51411   126.52969
30   185    고산    제주시   33.29382   126.16283
31   188    성산   서귀포시   33.38677    126.8802
32   189   서귀포   서귀포시   33.24616    126.5653
33   192    진주    진주시   35.16378   128.04004
34   201    강화    강화군   37.70739   126.44634
35   202    양평    양평군   37.48863   127.49446
36   203    이천    이천시   37.26399   127.48421
37   211    인제    인제군   38.05986   128.16714
38   212    홍천    홍천군    37.6836   127.88043
39   216    태백    태백시   37.17038   128.98929
40   221    제천    제천시   37.15928   128.19434
41   226    보은    보은군   36.48761   127.73415
42   232    천안    천안시   36.76217   127.29282
43   235    보령    보령시   36.32724   126.55744
44   236    부여    부여군   36.27242   126.92079
45   238    금산    금산군   36.10563   127.48175
46   243    부안    부안군   35.72961   126.71657
47   244    임실    임실군   35.61203   127.28556
48   245    정읍    정읍시   35.56337   126.83904
49   247    남원    남원시    35.4213   127.39652
50   248    장수    장수군   35.65696   127.52031
51   255   북창원    창원시   35.22655    128.6726
52   260    장흥    장흥군   34.68886   126.91951
53   261    해남    해남군   34.55375   126.56907
54   262    고흥    고흥군   34.61826   127.27572
55   271    봉화    봉화군   36.94361   128.91449
56   272    영주    영주시   36.87183   128.51688
57   273    문경    문경시   36.62727   128.14879
58   277    영덕    영덕군   36.53337   129.40926
59   278    의성    의성군    36.3561   128.68864
60   279    구미    구미시   36.13055   128.32056
61   281    영천    영천시   35.97742    128.9514
62   284    거창    거창군   35.66739    127.9099
63   285    합천    합천군   35.56505   128.16994
64   288    밀양    밀양시   35.49147   128.74413
65   289    산청    산청군     35.413    127.8791
66   294    거제    거제시   34.88818   128.60458
67   295    남해    남해군   34.81662   127.92641

### 2-7. 최단거리내의 대체 관측지점 탐색 및 대입

In [17]:
def dist(x_long, x_lati) :
    minLi = list()
    
    for idx in obPoints.index :
        long = pow(float(x_long) - float(obPoints.loc[idx]['경도']), 2)
        lati = pow(float(x_lati) - float(obPoints.loc[idx]['위도']), 2)
        minLi.append([np.sqrt(long + lati), obPoints.loc[idx]['주소']])
        
    return minLi[minLi.index(min(minLi))][1]

noItemCoordsDF['대체지점명'] = noItemCoordsDF.apply(lambda x : dist(x['경도'], x['위도']), axis = 1)
noItemCoordsDF.drop_duplicates(keep = 'first', inplace = True)
noItemCoordsDF

   시군구         위도          경도 대체지점명
0  예산군  36.680900  126.844738   서산시
1  정선군  37.380609  128.660871   평창군

### 2-8. 대체관측지점 추가

In [18]:
면적생산_대체지점 = pd.merge(면적생산_최대면적, noItemCoordsDF, left_on = '지역', right_on = '시군구', how = 'left')
면적생산_대체지점 = 면적생산_대체지점[['연도', '품명', '지역', '면적', '생산량', '대체지점명']]

## 대체지점있을 경우 적용, 없으면 기존 관측지점을 그대로 적용
def helper(x_ori, x_rep) :
    if pd.isna(x_rep) :
        return x_ori
    else :
        return x_rep

면적생산_대체지점['관측지점명'] = 면적생산_대체지점.apply(lambda x : helper(x['지역'], x['대체지점명']), axis = 1)
면적생산_대체지점.drop(['대체지점명'], axis = 1, inplace = True)
면적생산_대체지점.columns = ['연도', '품명', '지명' ,'면적', '생산량', '관측지점명']
면적생산_대체지점['연도'] = 면적생산_대체지점['연도'].apply(lambda x : str(x))
면적생산_대체지점

      연도  품명   지명    면적      생산량 관측지점명
0   2013   봄  예산군   120   383696   서산시
1   2014   봄  예산군    90   364326   서산시
2   2015   봄  예산군    60   287371   서산시
3   2016   봄  예산군   160   265919   서산시
4   2017   봄  예산군   280   519000   서산시
5   2018   봄  예산군   175   370000   서산시
6   2019   봄  문경시   318   270000   문경시
7   2020   봄  문경시   363   271700   문경시
8   2013  겨울  해남군  2842   348375   해남군
9   2014  겨울  해남군  2718   358017   해남군
10  2015  겨울  해남군  2918   294272   해남군
11  2016  겨울  해남군  2529   249841   해남군
12  2017  겨울  해남군  2306   258300   해남군
13  2018  겨울  해남군  3661   279900   해남군
14  2019  겨울  해남군  2640   437500   해남군
15  2020  겨울  해남군  2400   323100   해남군
16  2013  가을  해남군  1547  1593000   해남군
17  2014  가을  해남군  1648  1698000   해남군
18  2015  가을  해남군  1791  1436000   해남군
19  2016  가을  해남군  1851  1128000   해남군
20  2017  가을  해남군  1892  1362000   해남군
21  2018  가을  해남군  1993  1404000   해남군
22  2019  가을  해남군  1941  1113300   해남군
23  2020  가을  해남군  2488  1339700   해남군
24  2013  여름  정선군  1060   200895   평창군
25  2014  여름  평창군  1542   183287   평창군
26  2015  여름  정선군  1360   149607   평창군
27  2016  여름  정선군  1372   141239   평창군
28  2017  여름  평창군  1580   165000   평창군
29  2018  여름  평창군  1260   162000   평창군
30  2019  여름  평창군  1618   395453   평창군
31  2020  여름  평창군  1407   354656   평창군

### 2-9. 면적생산 merge

In [19]:
## 가뭄지수_종합유가 DF - 면적생산 DF Merge
가뭄지수_종합유가_면적생산 = pd.merge(가뭄지수_종합유가, 면적생산_대체지점, left_on = ['연도', '시군명'], right_on = ['연도', '관측지점명'], how = 'right')

가뭄지수_종합유가_면적생산.drop(['연도'], axis = 1, inplace = True)
가뭄지수_종합유가_면적생산 = 가뭄지수_종합유가_면적생산[['발표일자', '품명', '지점명', '시군명', '시도명', '지역', '관측지점명', '일반유가', '면세유가', '지명', '면적', '생산량',
#                                  'SPI1_가뭄단계_미판단', 'SPI1_가뭄단계_보통 가뭄', 'SPI1_가뭄단계_습함', 'SPI1_가뭄단계_심한 가뭄', 'SPI1_가뭄단계_약한 가뭄', 'SPI1_가뭄단계_정상', 
#                                  'SPI3_가뭄단계_미판단', 'SPI3_가뭄단계_보통 가뭄', 'SPI3_가뭄단계_습함', 'SPI3_가뭄단계_심한 가뭄', 'SPI3_가뭄단계_약한 가뭄', 'SPI3_가뭄단계_정상', 
#                                  'EDI_가뭄단계_극심한 가뭄', 'EDI_가뭄단계_미판단','EDI_가뭄단계_보통 가뭄', 'EDI_가뭄단계_습함', 'EDI_가뭄단계_심한 가뭄', 'EDI_가뭄단계_약한 가뭄', 'EDI_가뭄단계_정상']]
                                 'SPI1', 'SPI1_가뭄단계', 'SPI3', 'SPI3_가뭄단계', 'EDI','EDI_가뭄단계']]
가뭄지수_종합유가_면적생산

,발표일자,품명,지점명,시군명,시도명,지역,관측지점명,일반유가,면세유가,지명,면적,생산량,SPI1,SPI1_가뭄단계,SPI3,SPI3_가뭄단계,EDI,EDI_가뭄단계
0,2013-01-01,봄,서산,서산시,충남,충남,서산시,1763.88,1162.397362,예산군,120,383696,1.52,습함,1.38,습함,1.90,습함
1,2013-01-02,봄,서산,서산시,충남,충남,서산시,1763.05,1161.642817,예산군,120,383696,1.72,습함,1.41,습함,2.28,습함
2,2013-01-03,봄,서산,서산시,충남,충남,서산시,1762.56,1161.197362,예산군,120,383696,1.52,습함,1.40,습함,2.22,습함
3,2013-01-04,봄,서산,서산시,충남,충남,서산시,1762.05,1160.733726,예산군,120,383696,1.59,습함,1.44,습함,2.17,습함
4,2013-01-05,봄,서산,서산시,충남,충남,서산시,1761.49,1160.224635,예산군,120,383696,1.12,습함,1.45,습함,2.14,습함
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11671,2020-12-27,여름,대관령,평창군,강원,강원,평창군,1206.70,644.650000,평창군,1407,354656,-1.76,보통 가뭄,-2.12,심한 가뭄,-0.34,정상
11672,2020-12-28,여름,대관령,평창군,강원,강원,평창군,1208.46,645.440000,평창군,1407,354656,-1.65,보통 가뭄,-2.07,심한 가뭄,-0.34,정상
11673,2020-12-29,여름,대관령,평창군,강원,강원,평창군,1212.49,648.790000,평창군,1407,354656,-1.48,약한 가뭄,-2.03,심한 가뭄,-0.35,정상
11674,2020-12-30,여름,대관령,평창군,강원,강원,평창군,1215.67,651.480000,평창군,1407,354656,-1.45,약한 가뭄,-2.02,심한 가뭄,-0.35,정상
11675,2020-12-31,여름,대관령,평창군,강원,강원,평창군,1217.21,653.420000,평창군,1407,354656,-1.48,약한 가뭄,-2.37,심한 가뭄,-0.36,정상

# 3. (가뭄지수+종합유가 + 면적생산) + 수입량액

### 3-1. 수입량액 자료열 정리

In [20]:
수입량.drop(['수출(중량)', '수출(금액)', '수입(금액)'], axis = 1, inplace = True)
수입량.drop(수입량[수입량['월'] == '합'].index, inplace = True)
수입량.columns = ['연도', '월', '수입중량']

수입량['연도'] = 수입량['연도'].apply(lambda x : str(x))
수입량['월'] = 수입량['월'].apply(lambda x : str(x))

수입량['연월'] = 수입량['연도'] + '-' + 수입량['월']
수입량.drop(['연도', '월'], axis = 1, inplace = True)
수입량 = 수입량[['연월', '수입중량']]
수입량

          연월      수입중량
1    2013-01  616840.0
2    2013-02  278460.0
3    2013-03  234520.0
4    2013-04   31150.0
5    2013-05   24000.0
6    2013-06       0.0
7    2013-07       0.0
8    2013-08       0.0
9    2013-09  171305.0
10   2013-10   24000.0
11   2013-11       0.0
12   2013-12   22000.0
14   2014-01   44000.0
15   2014-02       0.0
16   2014-03       0.0
17   2014-04   24000.0
18   2014-05       0.0
19   2014-06   24000.0
20   2014-07       0.0
21   2014-08       0.0
22   2014-09   24000.0
23   2014-10   24000.0
24   2014-11       0.0
25   2014-12   48360.0
27   2015-01       0.0
28   2015-02   17000.0
29   2015-03    7000.0
30   2015-04   24000.0
31   2015-05       0.0
32   2015-06  253004.0
33   2015-07   16170.0
34   2015-08       0.0
35   2015-09       0.0
36   2015-10       0.0
37   2015-11       0.0
38   2015-12       0.0
40   2016-01   16200.0
41   2016-02       1.0
42   2016-03       0.0
43   2016-04       0.0
44   2016-05   57750.0
45   2016-06       0.0
46   2016-07       0.0
47   2016-08       0.0
48   2016-09  224520.0
49   2016-10       0.0
50   2016-11   50775.0
51   2016-12   31500.0
53   2017-01     120.0
54   2017-02       0.0
55   2017-03   23000.0
56   2017-04   15967.0
57   2017-05       0.0
58   2017-06       0.0
59   2017-07   14685.0
60   2017-08  109825.0
61   2017-09   86915.0
62   2017-10   37260.0
63   2017-11       0.0
64   2017-12       0.0
66   2018-01       0.0
67   2018-02   18326.0
68   2018-03       0.0
69   2018-04   48523.0
70   2018-05   16170.0
71   2018-06       0.0
72   2018-07       0.0
73   2018-08       0.0
74   2018-09       0.0
75   2018-10       0.0
76   2018-11       0.0
77   2018-12       0.0
79   2019-01   24000.0
80   2019-02   15000.0
81   2019-03       0.0
82   2019-04       1.7
83   2019-05       0.0
84   2019-06       0.0
85   2019-07       0.0
86   2019-08       0.0
87   2019-09       0.0
88   2019-10  276116.0
89   2019-11  135275.0
90   2019-12       0.0
92   2020-01       0.0
93   2020-02       0.0
94   2020-03       5.2
95   2020-04      24.0
96   2020-05       0.0
97   2020-06       0.0
98   2020-07       0.0
99   2020-08     500.0
100  2020-09  231980.0
101  2020-10  303057.7
102  2020-11    1610.0
103  2020-12  105600.0
105  2021-01       0.0
106  2021-02   15750.0
107  2021-03    7350.0
108  2021-04   12978.0
109  2021-05       0.0
110  2021-06    7350.0
111  2021-07    6028.0
112  2021-08       0.0
113  2021-09    1080.0
114  2021-10       0.0
115  2021-11       0.0
116  2021-12   16170.0

### 3-2. 수입량액 연월 정보 추가 및 발표일자 str화

In [21]:
가뭄지수_종합유가_면적생산['발표일자'] = 가뭄지수_종합유가_면적생산['발표일자'].apply(lambda x : str(x))
가뭄지수_종합유가_면적생산['연월'] = 가뭄지수_종합유가_면적생산['발표일자'].apply(lambda x : x[:7])

### 3-3. 수입량액 merge

In [22]:
가뭄지수_종합유가_면적생산_수입량액 = pd.merge(가뭄지수_종합유가_면적생산, 수입량, on = '연월', how = 'left')

가뭄지수_종합유가_면적생산_수입량액.drop(['연월'], axis = 1, inplace = True)
가뭄지수_종합유가_면적생산_수입량액 = 가뭄지수_종합유가_면적생산_수입량액[['발표일자', '품명', '지점명', '시군명', '시도명', '지역', '지명', '관측지점명', '일반유가', '면세유가',  '면적','생산량', '수입중량',
#                                            'SPI1_가뭄단계_미판단', 'SPI1_가뭄단계_보통 가뭄', 'SPI1_가뭄단계_습함', 'SPI1_가뭄단계_심한 가뭄', 'SPI1_가뭄단계_약한 가뭄', 'SPI1_가뭄단계_정상', 
#                                            'SPI3_가뭄단계_미판단', 'SPI3_가뭄단계_보통 가뭄', 'SPI3_가뭄단계_습함', 'SPI3_가뭄단계_심한 가뭄', 'SPI3_가뭄단계_약한 가뭄', 'SPI3_가뭄단계_정상', 
#                                            'EDI_가뭄단계_극심한 가뭄', 'EDI_가뭄단계_미판단','EDI_가뭄단계_보통 가뭄', 'EDI_가뭄단계_습함', 'EDI_가뭄단계_심한 가뭄', 'EDI_가뭄단계_약한 가뭄', 'EDI_가뭄단계_정상']]
                                           'SPI1', 'SPI1_가뭄단계', 'SPI3', 'SPI3_가뭄단계', 'EDI','EDI_가뭄단계']]

가뭄지수_종합유가_면적생산_수입량액

,발표일자,품명,지점명,시군명,시도명,지역,지명,관측지점명,일반유가,면세유가,면적,생산량,수입중량,SPI1,SPI1_가뭄단계,SPI3,SPI3_가뭄단계,EDI,EDI_가뭄단계
0,2013-01-01,봄,서산,서산시,충남,충남,예산군,서산시,1763.88,1162.397362,120,383696,616840.0,1.52,습함,1.38,습함,1.90,습함
1,2013-01-02,봄,서산,서산시,충남,충남,예산군,서산시,1763.05,1161.642817,120,383696,616840.0,1.72,습함,1.41,습함,2.28,습함
2,2013-01-03,봄,서산,서산시,충남,충남,예산군,서산시,1762.56,1161.197362,120,383696,616840.0,1.52,습함,1.40,습함,2.22,습함
3,2013-01-04,봄,서산,서산시,충남,충남,예산군,서산시,1762.05,1160.733726,120,383696,616840.0,1.59,습함,1.44,습함,2.17,습함
4,2013-01-05,봄,서산,서산시,충남,충남,예산군,서산시,1761.49,1160.224635,120,383696,616840.0,1.12,습함,1.45,습함,2.14,습함
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11671,2020-12-27,여름,대관령,평창군,강원,강원,평창군,평창군,1206.70,644.650000,1407,354656,105600.0,-1.76,보통 가뭄,-2.12,심한 가뭄,-0.34,정상
11672,2020-12-28,여름,대관령,평창군,강원,강원,평창군,평창군,1208.46,645.440000,1407,354656,105600.0,-1.65,보통 가뭄,-2.07,심한 가뭄,-0.34,정상
11673,2020-12-29,여름,대관령,평창군,강원,강원,평창군,평창군,1212.49,648.790000,1407,354656,105600.0,-1.48,약한 가뭄,-2.03,심한 가뭄,-0.35,정상
11674,2020-12-30,여름,대관령,평창군,강원,강원,평창군,평창군,1215.67,651.480000,1407,354656,105600.0,-1.45,약한 가뭄,-2.02,심한 가뭄,-0.35,정상
11675,2020-12-31,여름,대관령,평창군,강원,강원,평창군,평창군,1217.21,653.420000,1407,354656,105600.0,-1.48,약한 가뭄,-2.37,심한 가뭄,-0.36,정상

In [23]:
# ## For Debug.
# ## 일자 연속성 확인
# df = 가뭄지수_면세유가_면적생산_수입량액.sort_values('발표일자')

# df['발표일자'] = df['발표일자'].apply(lambda x : str(x))
# df['발표일자']

# prev_date = df['발표일자'].unique()[0]
# td = timedelta(days = 1)

# for dt in df['발표일자'].unique():
#     if dt != date.isoformat(date.fromisoformat(prev_date) + td) :
#         print(prev_date, dt)
#     prev_date = dt

In [24]:
# ## For Debug.
# ## 모든 일자 별로 사계절 가격 추출되었는지 확인

# df = 가뭄지수_면세유가_면적생산_수입량액

# for idx in df.index :
#     cnt = len(df[df['발표일자'] == df['발표일자'][idx]]['품명'].unique())
#     print (str(idx) + '/' + str(len(df.index)) + ' : ' + str(cnt))
#     if cnt != 4 :
#         print(idx)
#         break

# 4. (가뭄지수+면세유가 + 면적생산 + 수입량액) + 도매가(지역별)

### 4-1. 지역별 최종학습데이터셋 파일 저장

In [25]:
최종 = list()
for loc in ['서울', '부산', '대구', '광주', '대전'] :
    df = pd.read_csv(f'../data/도매가/보간/13_21_{loc}_도매가보간.csv', encoding = 'utf-8-sig', index_col = 0)
    df.drop('지역', axis = 1, inplace = True)
    
    최종학습데이터 = pd.merge(가뭄지수_종합유가_면적생산_수입량액, df, left_on = ['발표일자', '품명'], right_on = ['날짜', '품명'], how = 'right')
    최종학습데이터.dropna(inplace = True)
    최종학습데이터.drop(['날짜', 'SPI1_가뭄단계', 'SPI3_가뭄단계', 'EDI_가뭄단계'], axis = 1, inplace = True)
    
    최종학습데이터.rename(columns = {'발표일자' : '날짜'}, inplace = True)
    최종학습데이터 = 최종학습데이터[['날짜', '품명', '지역', '지명', '관측지점명', '일반유가', '면세유가', '면적', '생산량', '수입중량',
#                                 'SPI1_가뭄단계_미판단', 'SPI1_가뭄단계_보통 가뭄', 'SPI1_가뭄단계_습함', 'SPI1_가뭄단계_심한 가뭄', 'SPI1_가뭄단계_약한 가뭄', 'SPI1_가뭄단계_정상', 
#                                  'SPI3_가뭄단계_미판단', 'SPI3_가뭄단계_보통 가뭄', 'SPI3_가뭄단계_습함', 'SPI3_가뭄단계_심한 가뭄', 'SPI3_가뭄단계_약한 가뭄', 'SPI3_가뭄단계_정상', 
#                                  'EDI_가뭄단계_극심한 가뭄', 'EDI_가뭄단계_미판단','EDI_가뭄단계_보통 가뭄', 'EDI_가뭄단계_습함', 'EDI_가뭄단계_심한 가뭄', 'EDI_가뭄단계_약한 가뭄', 'EDI_가뭄단계_정상']]
                       'SPI1', 'SPI3', 'EDI', '도매가격']].reset_index(drop = True)
    
    최종학습데이터.to_csv(f'../data/result/입력/학습데이터1차_{loc}.csv', encoding = 'utf-8-sig')
    최종.append(최종학습데이터)

In [26]:
최종[0]

,날짜,품명,지역,지명,관측지점명,일반유가,면세유가,면적,생산량,수입중량,SPI1,SPI3,EDI,도매가격
0,2013-01-01,가을,전남,해남군,해남군,1742.89,1131.756969,1547.0,1593000.0,616840.0,1.96,0.97,2.11,13000.0
1,2013-01-02,가을,전남,해남군,해남군,1742.85,1131.720605,1547.0,1593000.0,616840.0,1.97,0.97,2.02,13000.0
2,2013-01-03,겨울,전남,해남군,해남군,1741.97,1130.920605,2842.0,348375.0,616840.0,1.85,0.97,1.93,12000.0
3,2013-01-04,겨울,전남,해남군,해남군,1741.97,1130.920605,2842.0,348375.0,616840.0,1.83,1.04,1.90,12000.0
4,2013-01-05,겨울,전남,해남군,해남군,1741.93,1130.884242,2842.0,348375.0,616840.0,1.73,1.07,1.85,12000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2909,2020-12-27,가을,전남,해남군,해남군,1196.84,615.350000,2488.0,1339700.0,105600.0,-3.81,-2.24,-0.01,3500.0
2910,2020-12-28,가을,전남,해남군,해남군,1201.25,615.730000,2488.0,1339700.0,105600.0,-1.46,-1.94,0.14,4000.0
2911,2020-12-29,가을,전남,해남군,해남군,1206.17,618.840000,2488.0,1339700.0,105600.0,-1.39,-1.92,0.11,4000.0
2912,2020-12-30,가을,전남,해남군,해남군,1209.83,623.170000,2488.0,1339700.0,105600.0,-0.96,-1.82,0.20,4000.0
2913,2020-12-31,가을,전남,해남군,해남군,1212.59,625.110000,2488.0,1339700.0,105600.0,-0.87,-1.85,0.17,4000.0

In [27]:
최종[4].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2914 entries, 0 to 2913
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      2914 non-null   object
 1   품명      2914 non-null   object
 2   지역      2914 non-null   object
 3   지명      2914 non-null   object
 4   관측지점명   2914 non-null   object
 5   일반유가    2914 non-null   float64
 6   면세유가    2914 non-null   float64
 7   면적      2914 non-null   float64
 8   생산량     2914 non-null   float64
 9   수입중량    2914 non-null   float64
 10  SPI1    2914 non-null   float64
 11  SPI3    2914 non-null   float64
 12  EDI     2914 non-null   float64
 13  도매가격    2914 non-null   float64
dtypes: float64(9), object(5)
memory usage: 318.8+ KB

### 최종학습데이터셋 조정 시 필요 데이터셋 저장

In [28]:
가뭄지수.to_csv("../data/result/입력/가뭄지수_최종정리.csv", encoding = "utf-8-sig")
일반유가_월별정리.to_csv("../data/result/입력/일반유가_최종정리.csv", encoding = "utf-8-sig")
면세유가_월별정리.to_csv("../data/result/입력/면세유가_최종정리.csv", encoding = "utf-8-sig")
면적생산_대체지점.to_csv("../data/result/입력/면적생산_최종정리.csv", encoding = "utf-8-sig")
수입량.to_csv("../data/result/입력/수입량_최종정리.csv", encoding = "utf-8-sig")