# 최종학습데이터셋_서울_Shift&Merge

### import

In [1]:
import os
import copy
import numpy as np
import pandas as pd
import statistics
import datetime
from datetime import date, timedelta
from dateutil.relativedelta import relativedelta
import datetime as dt 
import warnings
warnings.filterwarnings(action='ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 500)

### global

In [2]:
## 예측 대상 지역
loc = "서울"

## 데이터셋 shift 일수
shift = 60

### 전처리 데이터셋 input

In [3]:
## 전처리셋
가뭄지수 = pd.read_csv("../data/result/입력/가뭄지수_최종정리.csv", index_col = 0)
면적생산 = pd.read_csv("../data/result/입력/면적생산_최종정리.csv", index_col = 0)
일반유가 = pd.read_csv("../data/result/입력/일반유가_최종정리.csv", index_col = 0)
면세유가 = pd.read_csv("../data/result/입력/면세유가_최종정리.csv", index_col = 0)
수입량 = pd.read_csv("../data/result/입력/수입량_최종정리.csv", index_col = 0)
#도매가격 = pd.read_csv(f"../data/final/도매_가격_완성본_13_21년도_재수정.csv", index_col = 0)

## 한국행정구역분류표
addr = pd.read_excel('../data/지역/한국행정구역분류_2022.7.1.기준_20220630022706.xlsx', sheet_name = 1, header = [2, 2])
addr.drop('Unnamed: 0_level_0', axis = 1, inplace = True)
addr['시군구'].replace('예산시', '예산군')
addr.columns = addr.columns.droplevel(1)

## 21년도 도매가격 데이터
도매가격 = pd.read_csv(f"../data/도매가/보간/13_21_{loc}_도매가보간.csv", index_col = 0)

### 데이터셋 input (최종학습데이터)

In [4]:
data = pd.read_csv(f'../data/result/입력/학습데이터1차_{loc}.csv', index_col = 0)

### Shift

In [5]:
df_shift = copy.deepcopy(data)

In [6]:
## 연도 컬럼 추가
def helper(x) :
    if (pd.isna(x)) :
        return x
    else :
        return x[:4]

df_shift['도매가격품명'] = ''
df_shift['도매가격날짜'] = ''
df_shift['도매가격연도'] = ''
df_shift['도매가격품명'] = df_shift['품명']
df_shift['도매가격날짜'] = df_shift['날짜'].apply(lambda x : str(x))
df_shift['도매가격연도'] = df_shift['도매가격날짜'].apply(lambda x : helper(x))

df_shift = pd.concat([df_shift.loc[:, '날짜' : 'EDI'], df_shift.loc[:, '도매가격' : '도매가격연도'].shift(-1 * shift)], axis = 1)

### 21년 데이터 concat.

In [7]:
df_domae = 도매가격.drop('지역', axis = 1)
df_concat = df_shift.iloc[:, -4 :]

In [8]:
df_concat_droped = df_concat.dropna()

In [9]:
## 연도 컬럼 추가
def helper(x) :
    if (pd.isna(x)) :
        return x
    else :
        return x[:4]

df_domae.columns = ['도매가격날짜', '도매가격품명', '도매가격']
df_domae = df_domae[['도매가격', '도매가격품명', '도매가격날짜']]
df_domae['도매가격연도'] = df_domae['도매가격날짜'].apply(lambda x : helper(x))

In [10]:
## 기존 데이터셋에 없던 21년 이후 데이터를 추가
idx = 도매가격[도매가격['날짜'] == '2021-01-01'].index
df_domae = df_domae.iloc[idx[0] : idx[0] + shift, :]

In [11]:
df_concat_final = pd.concat([df_concat_droped, df_domae]).reset_index(drop = True)
df_concat_final

         도매가격 도매가격품명      도매가격날짜 도매가격연도
0     13000.0     겨울  2013-03-02   2013
1     13000.0     겨울  2013-03-03   2013
2     14000.0     겨울  2013-03-04   2013
3     14000.0     겨울  2013-03-05   2013
4     14000.0     겨울  2013-03-06   2013
...       ...    ...         ...    ...
2909   9000.0     겨울  2021-02-25   2021
2910  10400.0     겨울  2021-02-26   2021
2911  10400.0     겨울  2021-02-27   2021
2912  10400.0     겨울  2021-02-28   2021
2913  10400.0     겨울  2021-03-01   2021

[2914 rows x 4 columns]

In [12]:
df_shift_concat = copy.deepcopy(df_shift)

In [13]:
## 컬럼 정리
df_shift_concat.drop(columns = ['도매가격', '도매가격품명', '도매가격날짜', '도매가격연도'], axis = 1, inplace = True)
df_shift_concat = pd.concat([df_shift_concat, df_concat_final], axis = 1)

### 면적생산 merge

In [14]:
df_area = copy.deepcopy(df_shift_concat)

In [15]:
면적생산['연도'] = 면적생산['연도'].apply(lambda x : str(x))

In [16]:
# 연도 컬럼 추가
def helper(x) :
    if (pd.isna(x)) :
        return x
    else :
        return x[:4]


df_area['기존연도'] = df_area['날짜'].apply(lambda x : helper(x))

In [17]:
df_area = pd.merge(df_area, 면적생산, left_on = ['기존연도', '도매가격품명'], right_on = ['연도', '품명'], how = 'left')
df_area

,날짜,품명_x,지역,지명_x,관측지점명_x,일반유가,면세유가,면적_x,생산량_x,수입중량,SPI1,SPI3,EDI,도매가격,도매가격품명,도매가격날짜,도매가격연도,기존연도,연도,품명_y,지명_y,면적_y,생산량_y,관측지점명_y
0,2013-01-01,가을,전남,해남군,해남군,1742.89,1131.756969,1547.0,1593000.0,616840.0,1.96,0.97,2.11,13000.0,겨울,2013-03-02,2013,2013,2013,겨울,해남군,2842,348375,해남군
1,2013-01-02,가을,전남,해남군,해남군,1742.85,1131.720605,1547.0,1593000.0,616840.0,1.97,0.97,2.02,13000.0,겨울,2013-03-03,2013,2013,2013,겨울,해남군,2842,348375,해남군
2,2013-01-03,겨울,전남,해남군,해남군,1741.97,1130.920605,2842.0,348375.0,616840.0,1.85,0.97,1.93,14000.0,겨울,2013-03-04,2013,2013,2013,겨울,해남군,2842,348375,해남군
3,2013-01-04,겨울,전남,해남군,해남군,1741.97,1130.920605,2842.0,348375.0,616840.0,1.83,1.04,1.90,14000.0,겨울,2013-03-05,2013,2013,2013,겨울,해남군,2842,348375,해남군
4,2013-01-05,겨울,전남,해남군,해남군,1741.93,1130.884242,2842.0,348375.0,616840.0,1.73,1.07,1.85,14000.0,겨울,2013-03-06,2013,2013,2013,겨울,해남군,2842,348375,해남군
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2909,2020-12-27,가을,전남,해남군,해남군,1196.84,615.350000,2488.0,1339700.0,105600.0,-3.81,-2.24,-0.01,9000.0,겨울,2021-02-25,2021,2020,2020,겨울,해남군,2400,323100,해남군
2910,2020-12-28,가을,전남,해남군,해남군,1201.25,615.730000,2488.0,1339700.0,105600.0,-1.46,-1.94,0.14,10400.0,겨울,2021-02-26,2021,2020,2020,겨울,해남군,2400,323100,해남군
2911,2020-12-29,가을,전남,해남군,해남군,1206.17,618.840000,2488.0,1339700.0,105600.0,-1.39,-1.92,0.11,10400.0,겨울,2021-02-27,2021,2020,2020,겨울,해남군,2400,323100,해남군
2912,2020-12-30,가을,전남,해남군,해남군,1209.83,623.170000,2488.0,1339700.0,105600.0,-0.96,-1.82,0.20,10400.0,겨울,2021-02-28,2021,2020,2020,겨울,해남군,2400,323100,해남군
2913,2020-12-31,가을,전남,해남군,해남군,1212.59,625.110000,2488.0,1339700.0,105600.0,-0.87,-1.85,0.17,10400.0,겨울,2021-03-01,2021,2020,2020,겨울,해남군,2400,323100,해남군

### 일반유가 merge

In [18]:
df_taxoil = copy.deepcopy(df_area)

### 가뭄지수 관측지점의 시도명 추출 및 컬럼 추가

In [19]:
## 시도명 컬럼 추가 (time...)
df_taxoil['시도명'] = ''

## 시도명 탐색 후 대입
def helper(target) :
    if(pd.isna(target)) :
        return target
    
    try :
        ans = addr[addr['시군구'] == target].iloc[0]['시도']
    except :
        ans = addr[addr['시도'] == target].iloc[0]['시도']
        
    
        
    if ans[:2] in 면세유가['지역'].unique() :
        return ans[:2]
    else :
        return (ans[0] + ans[2])

df_taxoil['시도명'] = df_taxoil['지명_y'].apply(lambda x : helper(x))

In [20]:
df_taxoil = pd.merge(df_taxoil, 일반유가, left_on = ['날짜', '시도명'], right_on = ['날짜', '지역'], how = 'left')
df_taxoil

,날짜,품명_x,지역_x,지명_x,관측지점명_x,일반유가_x,면세유가,면적_x,생산량_x,수입중량,SPI1,SPI3,EDI,도매가격,도매가격품명,도매가격날짜,도매가격연도,기존연도,연도,품명_y,지명_y,면적_y,생산량_y,관측지점명_y,시도명,지역_y,일반유가_y
0,2013-01-01,가을,전남,해남군,해남군,1742.89,1131.756969,1547.0,1593000.0,616840.0,1.96,0.97,2.11,13000.0,겨울,2013-03-02,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1742.89
1,2013-01-02,가을,전남,해남군,해남군,1742.85,1131.720605,1547.0,1593000.0,616840.0,1.97,0.97,2.02,13000.0,겨울,2013-03-03,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1742.85
2,2013-01-03,겨울,전남,해남군,해남군,1741.97,1130.920605,2842.0,348375.0,616840.0,1.85,0.97,1.93,14000.0,겨울,2013-03-04,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1741.97
3,2013-01-04,겨울,전남,해남군,해남군,1741.97,1130.920605,2842.0,348375.0,616840.0,1.83,1.04,1.90,14000.0,겨울,2013-03-05,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1741.97
4,2013-01-05,겨울,전남,해남군,해남군,1741.93,1130.884242,2842.0,348375.0,616840.0,1.73,1.07,1.85,14000.0,겨울,2013-03-06,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1741.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2909,2020-12-27,가을,전남,해남군,해남군,1196.84,615.350000,2488.0,1339700.0,105600.0,-3.81,-2.24,-0.01,9000.0,겨울,2021-02-25,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1196.84
2910,2020-12-28,가을,전남,해남군,해남군,1201.25,615.730000,2488.0,1339700.0,105600.0,-1.46,-1.94,0.14,10400.0,겨울,2021-02-26,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1201.25
2911,2020-12-29,가을,전남,해남군,해남군,1206.17,618.840000,2488.0,1339700.0,105600.0,-1.39,-1.92,0.11,10400.0,겨울,2021-02-27,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1206.17
2912,2020-12-30,가을,전남,해남군,해남군,1209.83,623.170000,2488.0,1339700.0,105600.0,-0.96,-1.82,0.20,10400.0,겨울,2021-02-28,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1209.83
2913,2020-12-31,가을,전남,해남군,해남군,1212.59,625.110000,2488.0,1339700.0,105600.0,-0.87,-1.85,0.17,10400.0,겨울,2021-03-01,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1212.59

### 면세유가 merge

In [21]:
df_dutyfreeoil = copy.deepcopy(df_taxoil)

In [22]:
df_dutyfreeoil = pd.merge(df_dutyfreeoil, 면세유가, left_on = ['날짜', '시도명'], right_on = ['날짜', '지역'], how = 'left')
df_dutyfreeoil

,날짜,품명_x,지역_x,지명_x,관측지점명_x,일반유가_x,면세유가_x,면적_x,생산량_x,수입중량,SPI1,SPI3,EDI,도매가격,도매가격품명,도매가격날짜,도매가격연도,기존연도,연도,품명_y,지명_y,면적_y,생산량_y,관측지점명_y,시도명,지역_y,일반유가_y,지역,면세유가_y
0,2013-01-01,가을,전남,해남군,해남군,1742.89,1131.756969,1547.0,1593000.0,616840.0,1.96,0.97,2.11,13000.0,겨울,2013-03-02,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1742.89,전남,1131.756969
1,2013-01-02,가을,전남,해남군,해남군,1742.85,1131.720605,1547.0,1593000.0,616840.0,1.97,0.97,2.02,13000.0,겨울,2013-03-03,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1742.85,전남,1131.720605
2,2013-01-03,겨울,전남,해남군,해남군,1741.97,1130.920605,2842.0,348375.0,616840.0,1.85,0.97,1.93,14000.0,겨울,2013-03-04,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1741.97,전남,1130.920605
3,2013-01-04,겨울,전남,해남군,해남군,1741.97,1130.920605,2842.0,348375.0,616840.0,1.83,1.04,1.90,14000.0,겨울,2013-03-05,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1741.97,전남,1130.920605
4,2013-01-05,겨울,전남,해남군,해남군,1741.93,1130.884242,2842.0,348375.0,616840.0,1.73,1.07,1.85,14000.0,겨울,2013-03-06,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1741.93,전남,1130.884242
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2909,2020-12-27,가을,전남,해남군,해남군,1196.84,615.350000,2488.0,1339700.0,105600.0,-3.81,-2.24,-0.01,9000.0,겨울,2021-02-25,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1196.84,전남,615.350000
2910,2020-12-28,가을,전남,해남군,해남군,1201.25,615.730000,2488.0,1339700.0,105600.0,-1.46,-1.94,0.14,10400.0,겨울,2021-02-26,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1201.25,전남,615.730000
2911,2020-12-29,가을,전남,해남군,해남군,1206.17,618.840000,2488.0,1339700.0,105600.0,-1.39,-1.92,0.11,10400.0,겨울,2021-02-27,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1206.17,전남,618.840000
2912,2020-12-30,가을,전남,해남군,해남군,1209.83,623.170000,2488.0,1339700.0,105600.0,-0.96,-1.82,0.20,10400.0,겨울,2021-02-28,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1209.83,전남,623.170000
2913,2020-12-31,가을,전남,해남군,해남군,1212.59,625.110000,2488.0,1339700.0,105600.0,-0.87,-1.85,0.17,10400.0,겨울,2021-03-01,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1212.59,전남,625.110000

### 수입량 merge

In [23]:
df_import = copy.deepcopy(df_dutyfreeoil)

In [24]:
# 수입량 시점 전처리
def helper(x) :
    if (pd.isna(x)) :
        return x
    
    td = relativedelta(months = 1)
    newDate = pd.to_datetime(x) - td
    
    y = newDate.year
    m = newDate.month

    if (m % 10 == m) :
        m = '0' + str(m)
    else :
        pass

    return (str(y) + '-' + str(m))

# 도매가격연월 컬럼 추가
df_import['도매가격연월'] = df_import['도매가격날짜'].apply(lambda x : helper(x))

In [25]:
df_import = pd.merge(df_import, 수입량, left_on = '도매가격연월', right_on = '연월', how = 'left')
df_import

,날짜,품명_x,지역_x,지명_x,관측지점명_x,일반유가_x,면세유가_x,면적_x,생산량_x,수입중량_x,SPI1,SPI3,EDI,도매가격,도매가격품명,도매가격날짜,도매가격연도,기존연도,연도,품명_y,지명_y,면적_y,생산량_y,관측지점명_y,시도명,지역_y,일반유가_y,지역,면세유가_y,도매가격연월,연월,수입중량_y
0,2013-01-01,가을,전남,해남군,해남군,1742.89,1131.756969,1547.0,1593000.0,616840.0,1.96,0.97,2.11,13000.0,겨울,2013-03-02,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1742.89,전남,1131.756969,2013-02,2013-02,278460.0
1,2013-01-02,가을,전남,해남군,해남군,1742.85,1131.720605,1547.0,1593000.0,616840.0,1.97,0.97,2.02,13000.0,겨울,2013-03-03,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1742.85,전남,1131.720605,2013-02,2013-02,278460.0
2,2013-01-03,겨울,전남,해남군,해남군,1741.97,1130.920605,2842.0,348375.0,616840.0,1.85,0.97,1.93,14000.0,겨울,2013-03-04,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1741.97,전남,1130.920605,2013-02,2013-02,278460.0
3,2013-01-04,겨울,전남,해남군,해남군,1741.97,1130.920605,2842.0,348375.0,616840.0,1.83,1.04,1.90,14000.0,겨울,2013-03-05,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1741.97,전남,1130.920605,2013-02,2013-02,278460.0
4,2013-01-05,겨울,전남,해남군,해남군,1741.93,1130.884242,2842.0,348375.0,616840.0,1.73,1.07,1.85,14000.0,겨울,2013-03-06,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1741.93,전남,1130.884242,2013-02,2013-02,278460.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2909,2020-12-27,가을,전남,해남군,해남군,1196.84,615.350000,2488.0,1339700.0,105600.0,-3.81,-2.24,-0.01,9000.0,겨울,2021-02-25,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1196.84,전남,615.350000,2021-01,2021-01,0.0
2910,2020-12-28,가을,전남,해남군,해남군,1201.25,615.730000,2488.0,1339700.0,105600.0,-1.46,-1.94,0.14,10400.0,겨울,2021-02-26,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1201.25,전남,615.730000,2021-01,2021-01,0.0
2911,2020-12-29,가을,전남,해남군,해남군,1206.17,618.840000,2488.0,1339700.0,105600.0,-1.39,-1.92,0.11,10400.0,겨울,2021-02-27,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1206.17,전남,618.840000,2021-01,2021-01,0.0
2912,2020-12-30,가을,전남,해남군,해남군,1209.83,623.170000,2488.0,1339700.0,105600.0,-0.96,-1.82,0.20,10400.0,겨울,2021-02-28,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1209.83,전남,623.170000,2021-01,2021-01,0.0
2913,2020-12-31,가을,전남,해남군,해남군,1212.59,625.110000,2488.0,1339700.0,105600.0,-0.87,-1.85,0.17,10400.0,겨울,2021-03-01,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1212.59,전남,625.110000,2021-02,2021-02,15750.0

### 가뭄지수 merge

In [26]:
df_drought = copy.deepcopy(df_import)

In [27]:
df_drought = pd.merge(df_drought, 가뭄지수, left_on = ['날짜', '관측지점명_y'], right_on = ['발표일자', '시군명'], how = 'left')
df_drought

,날짜,품명_x,지역_x,지명_x,관측지점명_x,일반유가_x,면세유가_x,면적_x,생산량_x,수입중량_x,SPI1_x,SPI3_x,EDI_x,도매가격,도매가격품명,도매가격날짜,도매가격연도,기존연도,연도,품명_y,지명_y,면적_y,생산량_y,관측지점명_y,시도명_x,지역_y,일반유가_y,지역,면세유가_y,도매가격연월,연월,수입중량_y,발표일자,지점명,시군명,SPI1_y,SPI1_가뭄단계,SPI3_y,SPI3_가뭄단계,EDI_y,EDI_가뭄단계,시도명_y
0,2013-01-01,가을,전남,해남군,해남군,1742.89,1131.756969,1547.0,1593000.0,616840.0,1.96,0.97,2.11,13000.0,겨울,2013-03-02,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1742.89,전남,1131.756969,2013-02,2013-02,278460.0,2013-01-01,해남,해남군,1.96,습함,0.97,정상,2.11,습함,전남
1,2013-01-02,가을,전남,해남군,해남군,1742.85,1131.720605,1547.0,1593000.0,616840.0,1.97,0.97,2.02,13000.0,겨울,2013-03-03,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1742.85,전남,1131.720605,2013-02,2013-02,278460.0,2013-01-02,해남,해남군,1.97,습함,0.97,정상,2.02,습함,전남
2,2013-01-03,겨울,전남,해남군,해남군,1741.97,1130.920605,2842.0,348375.0,616840.0,1.85,0.97,1.93,14000.0,겨울,2013-03-04,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1741.97,전남,1130.920605,2013-02,2013-02,278460.0,2013-01-03,해남,해남군,1.85,습함,0.97,정상,1.93,습함,전남
3,2013-01-04,겨울,전남,해남군,해남군,1741.97,1130.920605,2842.0,348375.0,616840.0,1.83,1.04,1.90,14000.0,겨울,2013-03-05,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1741.97,전남,1130.920605,2013-02,2013-02,278460.0,2013-01-04,해남,해남군,1.83,습함,1.04,습함,1.90,습함,전남
4,2013-01-05,겨울,전남,해남군,해남군,1741.93,1130.884242,2842.0,348375.0,616840.0,1.73,1.07,1.85,14000.0,겨울,2013-03-06,2013,2013,2013,겨울,해남군,2842,348375,해남군,전남,전남,1741.93,전남,1130.884242,2013-02,2013-02,278460.0,2013-01-05,해남,해남군,1.73,습함,1.07,습함,1.85,습함,전남
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2909,2020-12-27,가을,전남,해남군,해남군,1196.84,615.350000,2488.0,1339700.0,105600.0,-3.81,-2.24,-0.01,9000.0,겨울,2021-02-25,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1196.84,전남,615.350000,2021-01,2021-01,0.0,2020-12-27,해남,해남군,-3.81,심한 가뭄,-2.24,심한 가뭄,-0.01,정상,전남
2910,2020-12-28,가을,전남,해남군,해남군,1201.25,615.730000,2488.0,1339700.0,105600.0,-1.46,-1.94,0.14,10400.0,겨울,2021-02-26,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1201.25,전남,615.730000,2021-01,2021-01,0.0,2020-12-28,해남,해남군,-1.46,약한 가뭄,-1.94,보통 가뭄,0.14,정상,전남
2911,2020-12-29,가을,전남,해남군,해남군,1206.17,618.840000,2488.0,1339700.0,105600.0,-1.39,-1.92,0.11,10400.0,겨울,2021-02-27,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1206.17,전남,618.840000,2021-01,2021-01,0.0,2020-12-29,해남,해남군,-1.39,약한 가뭄,-1.92,보통 가뭄,0.11,정상,전남
2912,2020-12-30,가을,전남,해남군,해남군,1209.83,623.170000,2488.0,1339700.0,105600.0,-0.96,-1.82,0.20,10400.0,겨울,2021-02-28,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1209.83,전남,623.170000,2021-01,2021-01,0.0,2020-12-30,해남,해남군,-0.96,정상,-1.82,보통 가뭄,0.20,정상,전남
2913,2020-12-31,가을,전남,해남군,해남군,1212.59,625.110000,2488.0,1339700.0,105600.0,-0.87,-1.85,0.17,10400.0,겨울,2021-03-01,2021,2020,2020,겨울,해남군,2400,323100,해남군,전남,전남,1212.59,전남,625.110000,2021-02,2021-02,15750.0,2020-12-31,해남,해남군,-0.87,정상,-1.85,보통 가뭄,0.17,정상,전남

### 컬럼 정리

In [28]:
df_columns = copy.deepcopy(df_drought)

In [29]:
# drop 제외 대상
protected = ['날짜', '도매가격', '도매가격품명', '도매가격날짜', '지명_y', '면적_y', '생산량_y', 
             '관측지점명_y', '시도명_y', '일반유가_y', '면세유가_y', '수입중량_y', 'SPI1_y',  'SPI3_y', 'EDI_y']

In [30]:
li = []
for item in list(df_columns.columns) :
    if not item in protected :
        li.append(item)
        
df_columns = df_columns.drop(columns = li)
df_columns

,날짜,도매가격,도매가격품명,도매가격날짜,지명_y,면적_y,생산량_y,관측지점명_y,일반유가_y,면세유가_y,수입중량_y,SPI1_y,SPI3_y,EDI_y,시도명_y
0,2013-01-01,13000.0,겨울,2013-03-02,해남군,2842,348375,해남군,1742.89,1131.756969,278460.0,1.96,0.97,2.11,전남
1,2013-01-02,13000.0,겨울,2013-03-03,해남군,2842,348375,해남군,1742.85,1131.720605,278460.0,1.97,0.97,2.02,전남
2,2013-01-03,14000.0,겨울,2013-03-04,해남군,2842,348375,해남군,1741.97,1130.920605,278460.0,1.85,0.97,1.93,전남
3,2013-01-04,14000.0,겨울,2013-03-05,해남군,2842,348375,해남군,1741.97,1130.920605,278460.0,1.83,1.04,1.90,전남
4,2013-01-05,14000.0,겨울,2013-03-06,해남군,2842,348375,해남군,1741.93,1130.884242,278460.0,1.73,1.07,1.85,전남
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2909,2020-12-27,9000.0,겨울,2021-02-25,해남군,2400,323100,해남군,1196.84,615.350000,0.0,-3.81,-2.24,-0.01,전남
2910,2020-12-28,10400.0,겨울,2021-02-26,해남군,2400,323100,해남군,1201.25,615.730000,0.0,-1.46,-1.94,0.14,전남
2911,2020-12-29,10400.0,겨울,2021-02-27,해남군,2400,323100,해남군,1206.17,618.840000,0.0,-1.39,-1.92,0.11,전남
2912,2020-12-30,10400.0,겨울,2021-02-28,해남군,2400,323100,해남군,1209.83,623.170000,0.0,-0.96,-1.82,0.20,전남
2913,2020-12-31,10400.0,겨울,2021-03-01,해남군,2400,323100,해남군,1212.59,625.110000,15750.0,-0.87,-1.85,0.17,전남

In [31]:
df_columns.columns = ['날짜', '도매가격', '도매가격품명', '도매가격날짜', '지명', '면적', '생산량', '관측지점명',
                 '일반유가', '면세유가', '수입중량(30일전)', 'SPI1', 'SPI3', 'EDI', '시도명']
df_columns = df_columns[['날짜', '도매가격품명', '지명', '시도명', '관측지점명', '면적', '생산량', 'SPI1', 'SPI3', 'EDI', 
               '일반유가', '면세유가', '수입중량(30일전)', '도매가격날짜', '도매가격']]
df_columns

,날짜,도매가격품명,지명,시도명,관측지점명,면적,생산량,SPI1,SPI3,EDI,일반유가,면세유가,수입중량(30일전),도매가격날짜,도매가격
0,2013-01-01,겨울,해남군,전남,해남군,2842,348375,1.96,0.97,2.11,1742.89,1131.756969,278460.0,2013-03-02,13000.0
1,2013-01-02,겨울,해남군,전남,해남군,2842,348375,1.97,0.97,2.02,1742.85,1131.720605,278460.0,2013-03-03,13000.0
2,2013-01-03,겨울,해남군,전남,해남군,2842,348375,1.85,0.97,1.93,1741.97,1130.920605,278460.0,2013-03-04,14000.0
3,2013-01-04,겨울,해남군,전남,해남군,2842,348375,1.83,1.04,1.90,1741.97,1130.920605,278460.0,2013-03-05,14000.0
4,2013-01-05,겨울,해남군,전남,해남군,2842,348375,1.73,1.07,1.85,1741.93,1130.884242,278460.0,2013-03-06,14000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2909,2020-12-27,겨울,해남군,전남,해남군,2400,323100,-3.81,-2.24,-0.01,1196.84,615.350000,0.0,2021-02-25,9000.0
2910,2020-12-28,겨울,해남군,전남,해남군,2400,323100,-1.46,-1.94,0.14,1201.25,615.730000,0.0,2021-02-26,10400.0
2911,2020-12-29,겨울,해남군,전남,해남군,2400,323100,-1.39,-1.92,0.11,1206.17,618.840000,0.0,2021-02-27,10400.0
2912,2020-12-30,겨울,해남군,전남,해남군,2400,323100,-0.96,-1.82,0.20,1209.83,623.170000,0.0,2021-02-28,10400.0
2913,2020-12-31,겨울,해남군,전남,해남군,2400,323100,-0.87,-1.85,0.17,1212.59,625.110000,15750.0,2021-03-01,10400.0

### 최종데이터셋 파일 저장

In [32]:
loc

'서울'

In [33]:
df_result = copy.deepcopy(df_columns)
df_result.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2914 entries, 0 to 2913
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   날짜          2914 non-null   object
 1   도매가격품명      2914 non-null   object
 2   지명          2914 non-null   object
 3   시도명         2914 non-null   object
 4   관측지점명       2914 non-null   object
 5   면적          2914 non-null   int64
 6   생산량         2914 non-null   int64
 7   SPI1        2914 non-null   float64
 8   SPI3        2914 non-null   float64
 9   EDI         2914 non-null   float64
 10  일반유가        2914 non-null   float64
 11  면세유가        2914 non-null   float64
 12  수입중량(30일전)  2914 non-null   float64
 13  도매가격날짜      2914 non-null   object
 14  도매가격        2914 non-null   float64
dtypes: float64(7), int64(2), object(6)
memory usage: 364.2+ KB

In [34]:
df_result.to_csv(f"../data/result/출력/최종학습데이터_{loc}.csv", encoding = 'utf-8-sig')